project_type: android
test:
  build:
    command: gradle :app:assembleDebug
  checkstyle:
    command: gradle :app:checkstyle
  findbugs:
    command: gradle :app:findbugs
  pmd:
    command: gradle :app:pmd
  androidlint:
    command: gradle :app:lintDebug
